// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3bpzUf5UI1_Shs62GTOCdwPLJLMXgq4',
    appId: '1:654450451057:web:e9d3b8aa873f7cbe3471d0',
    messagingSenderId: '654450451057',
    projectId: 'craftmyplate-test',
    authDomain: 'craftmyplate-test.firebaseapp.com',
    storageBucket: 'craftmyplate-test.appspot.com',
    measurementId: 'G-YNPGMVT589',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxh07Deu7-UiYmIUNl6CFEuk5BVSlor_I',
    appId: '1:654450451057:android:4196b3cea1d3b0373471d0',
    messagingSenderId: '654450451057',
    projectId: 'craftmyplate-test',
    storageBucket: 'craftmyplate-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7S7tMb0Bp7i3V3rwn_dkhhVaVFuSDwRQ',
    appId: '1:654450451057:ios:b8e2e9d2e1105cc83471d0',
    messagingSenderId: '654450451057',
    projectId: 'craftmyplate-test',
    storageBucket: 'craftmyplate-test.appspot.com',
    iosClientId: '654450451057-5jh60a19se5hccf6jgcpe9o3t8g8qd9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7S7tMb0Bp7i3V3rwn_dkhhVaVFuSDwRQ',
    appId: '1:654450451057:ios:e97074167106aedf3471d0',
    messagingSenderId: '654450451057',
    projectId: 'craftmyplate-test',
    storageBucket: 'craftmyplate-test.appspot.com',
    iosClientId: '654450451057-sqk5td8pm0lpphe6g2tvctutb6kotk09.apps.googleusercontent.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
